### ISSUE TITLE
Use an icon font for all non-custom icons?

### ISSUE THREAD

**Issue by davelab6** [MFEK/glif#105]
<img width="343" alt="Screen Shot 2021-05-10 at 12 07 30" src="https://user-images.githubusercontent.com/261579/117689984-52ef1180-b188-11eb-9d41-7cca722ab525.png">

The icons for add/remove/up/down are aligned oddly; the up/down look like unicode characters typeset with a system font, whereas the add/remove look like icons rendered from vector artwork. 

I suggest using a comprehensive UI icon set packaged as a font, like the Material Design set on https://fonts.google.com/icons, so that you can get the best of both worlds

**Comment by ctrlcctrlv** [comment]
This issue will be closed by #99.

![image](https://user-images.githubusercontent.com/838783/118187781-6eb71980-b40d-11eb-99e6-13908d90c55a.png)

For @MatthewBlanchard, I'm pasting here the charmap.

![Screenshot_20210513_165748](https://user-images.githubusercontent.com/838783/118187720-51824b00-b40d-11eb-83d1-9000e5c53921.png)

I didn't add the UTF-8 for every new icon this time, so when you want to use a new icon, select it from here. I'll do the same. :-)
