### ISSUE TITLE
Building from release fails

### ISSUE THREAD

**Issue by romgrk** [MFEK/glif#111]
Just a heads up, building this from the [release source](https://github.com/MFEK/glif/releases/tag/1.0a) fails with the following error:

```
error: git describe failed with status 128: fatal: not a git repository (or any of the parent directories): .git
  --> src/util/argparser.rs:21:40
   |
21 |         .version(&*format!("{}-alpha", git_version!()))
   |                                        ^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `proc_macro_call` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Probably best to just install it from a git clone anyway but I wanted to share just so you know.

**Comment by ctrlcctrlv** [comment]
Oh, that's interesting. I guess that the release tar ball doesn't pack a Git repository. Thanks for the note, I'll fix it
