### ISSUE TITLE
Proposal: refactor namespaces so the binary comes out as `mfek-glif`

### ISSUE THREAD

**Issue by alerque** [MFEK/glif#112]
I would like to setup Arch Linux packaging for this project, but right away I'm faced with some guideline problems. Naming the package is difficult. I would like to propose some upstream reorganization here to make downstream usage more consistent.

The biggest issue is that capital letters in binary names are *strongly* discouraged. Guidelines on this vary by distro. I know there are a few distros that 100% enforce this and there are some that don't care at all. Arch Linux is somewhere in the middle: it strongly dislikes them but has allowed a few exceptions. For example historical reasons have given `X` a pass. There are also a handful of others. Many more projects are relegated to keeping their upstream capitalized versions to the side and linking a lowercased version from `/bin`. For example Virtual Box, whose upstream binary name comes out as `VBoxManage` is symlinked from `vboxmanage`.

For Arch Linux packaging, upper casing the name of the package is completely disallowed, I can't even submit a package except in lower case. The binary inside doesn't have to match the package name, but I would probably need to at the very least symlink a lower cased version or more likely just lower case it after build.

I would like to recommend that this project adopt a naming scheme that will be more likely to be implemented with no changes downstream: Lets rename the binary generated here from `MEFKglif` → `mefk-glif`. That will still leave room for other binaries in the `mefk-...` namespace. It will also make it easier to search for packages (dashes as separators help by virtue of being valid word boundary so "whole word" searches for `glif` or `mefk` will come up positive. The dash notation for subcommands is also pretty widely recognized these days (cf. `git-...`).

I do realize there is a bit of a hyphen vs. underscore fiasco in progress in the world of Rust crates. Avoiding the whole thing would be the biggest reason to not add the dash, but honestly I think it will be better off

If this is agreeable I'd be happy to put it together as a PR.

Alternatively, simply `glif` might actually work as a package & binary name. I initially assumed that would be a hard name to claim, but I [don't actually see anything in that namespace](https://repology.org/projects/?search=glif) at all in any major distro.

**Comment by ctrlcctrlv** [comment]
Hello—

This certainly would have presented an IPC problem if you tried to use MFEKglif prior to 553c65e, as I hardcoded the binary name. Now, you can have on the target system _either_ `MFEKmetadata` or `mfek-metadata` and it's recognized.

Packagers will need to decide for themselves what name makes sense for their OS and its guidelines. I like the names how they are. Now you can just do this in a build script:

```bash
mv MFEKglif mfek-glif
mv MFEKmetadata mfek-metadata
mv MFEKstroke mfek-stroke
```

And everything will continue to work as expected.

**Comment by ctrlcctrlv** [comment]
Is that fix all right with you @alerque? I understand that some distributions don't like capitalized binary names, but I like them, and think they make a lot of sense on Windows.

I figure that Linux distributions are going to want to make even more changes to MFEK. For example, I _think_ they are going to want to take certain `.rlib`'s, especially `glifparser`, but maybe also `rust-skia` and `rust-sdl2`, large crates that we're reusing a lot between statically compiled binaries, and dynamically link them to save space. I figure that they're going to want to do an atypical build, in release mode with a `upx` run afterwards. So, given that the build is already going to be unusual…I don't think that `mv` is the biggest problem you have.

**Comment by ctrlcctrlv** [comment]
Like especially for example when we have `MFEKufo` public and not just haunting my personal hard drive, that's a ton of shared libraries between MFEKufo, MFEKglif and MFEKabout. MFEKstroke also shares glifparser.rlib, as does MFEKmetadata. I really doubt that the best way to distribute on Linux is anything like a typical build.

**Comment by alerque** [comment]
True, most (not all) distros are going to want some dynamic links to save space and offer modular updates. Rust doesn't make that easy, but in this case I'm sure there will be things....

With this namespacing concession in mind I already setup a [mfek-glif](https://aur.archlinux.org/packages/mfek-glif) package (also available in a `-git` variant) and will work on the others.

Probably the biggest concern in having alternative names will be in documentation. Given that Windows (and even macOS) are more likely to launch commands from an icon than a terminal it would have made sense to me to just universally keep lower case bin names with upper case variants in the respective launchers, but whatevez....
