### ISSUE TITLE
Mfek UFO: proportional width cells, etc

### ISSUE THREAD

**Issue by davelab6** [MFEK/glif#116]
(filing here and you can transfer to the ufo repo when you make it public)

https://twitter.com/fr_brennan/status/1397723808191156230?s=19 shows a typical glyph view grid:

![20210527_062637](https://user-images.githubusercontent.com/261579/119810932-87ffa180-beb4-11eb-9d77-c2ddafa2aa40.jpg)

One of the early mocks Eli did for [runebender](https://github.com/linebender/runebender/issues/43#issuecomment-616755293) showed proportionally spaced cells, 

![](https://user-images.githubusercontent.com/5162664/79790200-64fdd800-8319-11ea-8a7b-5abcbb4cc157.png)

But the current runebender uses a monospace grid, with eliding longer glyph names and overflow of larger glyphs, like the honorific here:

![](https://user-images.githubusercontent.com/5162664/81531963-a3dbe800-9331-11ea-9c23-a858557b23ea.png)

- [ ] So I think a "scale factor" (like Glyphsapp and Robofont and fontlab have, with a slider on the bottom toolbar, and fontforge has as a set of size options in the view pulldown, as I recall), can be complimented by a 
- [ ] monospace default with a proportional toggle, and
- [ ] theming for the background, cell border, cell background, foreground, label bg/fg color, label eliding technique (2+ lines, middle ellipsis, end ellipsis, etc)

**Comment by ctrlcctrlv** [comment]
lol sometimes I forget how ugly Runebender's UI is. Yeah, that's bad.

Well, the interesting thing about MFEKufo is that it uses Dear Imgui for everything…which already has a ton of available themes. So theming is already there even without me doing anything.

Ellipsis are also provided by Imgui.

I need to check, but I _think_ proportional display is doable through Imgui. Although, perhaps not with the grid method Matt used. I'll have to verify that.

I will indeed transfer this to MFEK/ufo when it's public.

**Comment by ctrlcctrlv** [comment]
As anticipated, this won't be an issue.

![image](https://user-images.githubusercontent.com/838783/120055966-5519f280-c007-11eb-8ed9-e84d5b21a3fa.png)

Closing as first release of MFEKufo will have all of this just as a result of the fact we're not rolling our own GUI.
