### ISSUE TITLE
Change selected off curve and corner points selection color.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#130]
Suggested by Dave Crossland on Twitter. I think this is a good idea and will look into this soon after finishing the image tool.

**Comment by davelab6** [comment]
https://twitter.com/MattRBlanchard/status/1412822359610888197?s=19

**Comment by MatthewBlanchard** [comment]
Added this in the main branch. Created issue for finding more aesthetically pleasing/consistent colors. Closing this.
