### ISSUE TITLE
Sometimes with the grid enabled trying to draw with the pen tool causes a panic.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#134]
I've been unable to reliably recreate this bug, but it's a pretty high priority. I'm not sure how or why it even happens. If anyone @ctrlcctrlv runs into this bug again a stack trace or repeatable instructions would be worth the world to me.

**Comment by ctrlcctrlv** [comment]
I rewrote grid tool and doubt this still happens, but if it does , I will reopen a bug with more details.
