### ISSUE TITLE
Sometimes when exporting the layer 0 in the UFO data does not match that in the JSON MFEK data.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#135]
We're considering abandoning the idea of using the UFO file format as our internal format, and simply using JSON that's converted back upon export. The problem being when external tools are used they might modify layer 0 and make MFEK data attached to that layer. There are two ways to solve this problem:

1. Check our internal layer 0 against the UFO layer 0 and prompt the user to clear the associated MFEK data.
2. Abandon the idea of trying to maintain a UFO compatible layer 0 and save only in JSON format until export.

**Comment by ctrlcctrlv** [comment]
I believe I just fixed this in 4ae573f3778356c843a02a57a90e02dff424bdfa.
