### ISSUE TITLE
Selected points now have different colors depending on point types, but the colors should be adjusted to be more aesthetically pleasing.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#136]
I'm not the best at this type of thing so I'd really love some input on what the colors should look like. 
![Capture](https://user-images.githubusercontent.com/310356/125207659-6d626b80-e25b-11eb-8a89-e6a00446fe63.PNG)

**Comment by ctrlcctrlv** [comment]
(lgtm)
