### ISSUE TITLE
Change internal representation of background images.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#137]
Currently the way we store images is problematic in a few ways. We're holding an affine matrix that represents the image transform, which works, but decomposing this matrix back into scale, rotation, shear, etc. is somewhat complicated and introduces rounding errors.

I'd like to change it so if we load an existing image from a UFO it maintains it's matrix, but when a user adds a new image through MFEK we keep scale, shear, rotation, etc. as separate variables the user can modify and then composes the matrix each frame. This allows users to easily specify very specific angles they want the image to appear at, and does not introduce rounding errors to the values the users see on the user interfaces (ex 45 -> 45.00006 after decomposition). On export we'd compose an affine matrix out of these values and store it in the standard manner for UFO images.

On the topic of a user importing images the image would not be able to be modified in this way until the user clicks a button to clear the existing matrix, and then our method would take over from there.

**Comment by ctrlcctrlv** [comment]
With Matt having left, this is up to me to decide…I believe 4ae573f will cause fewer round trips, and also intended images as a simple guide for drawing where major exactitude wouldn't be expected. Therefore, I'm closing this as I'll certainly never get around to fixing it.
