### ISSUE TITLE
Replicate Inkscape's measurement tool.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#142]
While working me and Fred decided that our measurement tool doesn't exactly measure up Inkscape's. We'd like to replicate inkscape's measure tool for our own.

**Comment by davelab6** [comment]
Kindly, I believe this is high priority, because measuring is important when refining the system of shapes in a typeface.

**Comment by ctrlcctrlv** [comment]
@davelab6 in that case you'll be pleased to know closing this is part of the grant that makes up matt's october grant from MFEK Fndn Inc (me)
