### ISSUE TITLE
VWS handles don't draw on the first point in a contour.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#150]
I am pretty sure I understand why this is happening, I just wanted to make a note of it before I forget.

When VWS was first added to the editor you couldn't make open paths, and I think I disabled drawing on the 0th point in a contour so you didn't get two separate handles drawing in the same spot. This should be a matter of adding a check.

**Comment by ctrlcctrlv** [comment]
They do now.

![image](https://user-images.githubusercontent.com/838783/140611169-bbd5d68b-3a64-42aa-bbd5-032a44a75d89.png)
