### ISSUE TITLE
VWS handles should have editable angle/width in the dialog box.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#152]
I noticed this when doing the drawing demo. I think it'd be nice to be able to specify the exact width in units so that you could match the width/angle of two handles to each other.

**Comment by ctrlcctrlv** [comment]
Seems done

![image](https://user-images.githubusercontent.com/838783/140642888-e6862a8e-a189-4ffa-8fcb-331e7f144814.png)
