### ISSUE TITLE
Middle-click pan

### ISSUE THREAD

**Issue by ctrlcctrlv** [MFEK/glif#200]
@fontfish emailed request №1

> Being able to use the mouse scroll wheel to move the viewspace would make for a much smoother editing experience […]

**Comment by fontfish** [comment]
Thank you very much, @ctrlcctrlv. As mentioned, you've got the wrong Greg(or) there. Might be best to un-tag them if you can.

**Comment by gvwilson** [comment]
Yes - I'd be grateful if you could untag me.

**Comment by ctrlcctrlv** [comment]
Sorry about that. I updated the issues affected, removing @/gvwilson's name and adding @fontfish. I'm not otherwise in control of subscriptions, so @/gvwilson you can click “Unsubscribe”.

**Comment by ctrlcctrlv** [comment]
As I said via email I don't use a three button mouse, find them inconvenient partially due to physical disability and won't be working on this personally

**Comment by MatthewBlanchard** [comment]
This has been fixed by the toolbehavior commit.
