### ISSUE TITLE
Scroll wheel zoom

### ISSUE THREAD

**Issue by ctrlcctrlv** [MFEK/glif#201]
@fontfish emailed request №2

> [B]eing able to hold down a modifier key and use the mouse wheel to zoom […] would make for a much smoother editing experience

**Comment by fontfish** [comment]
See my comment on [issue request №1](https://github.com/MFEK/glif/issues/200#issuecomment-974523433).

**Comment by ctrlcctrlv** [comment]
Solved in https://github.com/MFEK/glif/commit/c4f7fb0088f7af2f68943f41874ec7985a6ac12a.
