### ISSUE TITLE
artifacts stop downloading halfway

### ISSUE THREAD

**Issue by brigazvi** [MFEK/glif#210]
I'm trying to download the artifact for windows. the file I get is 7.9Mb, sometimes smaller. when it should be 23.8Mb.
I'm trying to open the examples with the 7.9Mb downloaded file, I get this error:
![תמונה](https://user-images.githubusercontent.com/37640970/144137673-5b562123-6fff-4c3e-992d-7054c482febe.png)

maybe we should make a alpha release after all.

**Comment by ctrlcctrlv** [comment]
Hey, thanks for the note. Not too much I can do about GitHub's servers of course…I have a very massive private branch on my PC right now〜

![image](https://user-images.githubusercontent.com/838783/144199550-1cef83df-50fa-40be-9e89-e133a12fc910.png)

I was actually planning to submit our first binary pre-release when I merge this branch (it adds guidelines, but also a whole bunch of other stuff—it deprecates `calc_x` and `calc_y`, all matrix calculations are now done on `Viewport`, it has a fixed grid.rs that works with Rotalics, and a bunch of other fixes I've been working on. @prajwalprabhu is doing some work with me over on MFEK/math.rlib regarding simplification that might also get into that release.

We're making good progress I think, we had a bumpy two weeks, not gonna sugarcoat it, but stuff's back on track and we're gonna “Build Back Better™” (with apologies to Joe Biden).

**Comment by ctrlcctrlv** [comment]
Artifacts are now much smaller; nothing I can do about GitHub's servers; main issue for binary woes is going to be #219.
