### ISSUE TITLE
macOS 11.6 arm64 build error: `failed to select a version for the requirement arboard = "=2.0.1"`

### ISSUE THREAD

**Issue by eliheuer** [MFEK/glif#236]
I have the Vulkan SDK installed but get this error when trying to build on macOS 11.6, Arm(Mac Mini 2020).
```
failed to select a version for the requirement `arboard = "=2.0.1"`
```
<img width="1920" alt="Screen_Shot_2022-01-03_at_10 03 25_PM" src="https://user-images.githubusercontent.com/5162664/148016612-49d8232b-0ba3-4176-8d7c-fda4d368ad1d.png">

**Comment by eliheuer** [comment]
Running `rm -rf ~/.cargo/registry` got me past this error, lol. closing this since it is probably something with my system and wouldn't happen with a clean install.

I get another error now, but I'll look into this a bit first before making an issue.
<img width="1920" alt="Screen Shot 2022-01-03 at 10 37 00 PM" src="https://user-images.githubusercontent.com/5162664/148019244-9437a541-af87-465d-b792-52aa321f54cd.png">

**Comment by ctrlcctrlv** [comment]
MFEKglif no longer needs nightly compiler, it works in stable. There seems to be a mismatch between compiler you're using and compiler expected.

By the way, that last command has two problems. First, args for MFEKglif need to come after `--`. Second, to repeat once again, _you must not try to give MFEKglif a UFO path_. It won't work. I'm not positive what will happen, but it almost definitely rhymes with rash and starts with letter ‹c›. :wink:

**Comment by ctrlcctrlv** [comment]
And, no matter how far advanced MFEK project is, giving MFEKglif a UFO path will never work. (Although, hopefully in future you'll get an explanatory error, telling you you need to run `MFEKufo` or `MFEKdesignspace`, neither of which exist today, rather than a crash.)
