### ISSUE TITLE
Suggestion for improving edit/history API in the editor.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#291]
```rs
let glyphModification = editor.beginModification()
glyphModification.inner.blah = foo // I'm a wrapper around a mutable reference to glyph!
editor.endModification(glyphModification)
```

Get rid of the extra scope created by the anonymous function that's currently used for glyph modifications, and instead just return a mutable reference to the glyph after calling begin mod and consume it in end mod.

This will help in a variety of ways:

Cleaner code, fewer indentations, less scopes.
No need to copy, clone, move data between the scopes.
More rusty.

There's also the potential of not having an endModification at all, and simply ending the edit when the token is dropped, but I don't think this is explicit enough. I'd argue that I'd rather have drop(glyphModification) panic at runtime unless editor.endModification() is called.

**Comment by MatthewBlanchard** [comment]
get_active_layer() now simply returns a normal old reference. You might have to wrap it in a block for borrowing reasons, but there's no longer closures involved.

**Comment by ctrlcctrlv** [comment]
Right, so this is done then I take it :)
