### ISSUE TITLE
On Wayland + Gnome 3 window resizing causes visual artifacts.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#295]
Doesn't seem like a huge deal, but I figured I'd note it down somewhere. When you resize the windows in Wayland + Gnome3 it tears as if vertical sync was off, but the image being "refreshed" is rgb 0 0 0 so you get these strange half-rendered frames.

Don't have screen capture right now, but will append a video to this issue soon.

**Comment by ctrlcctrlv** [comment]
I think it's on all systems, no need for video :)

**Comment by ctrlcctrlv** [comment]
Closing in favor of #322 as the issue is in all systems, macOS just handles the missing frames differently (by applying scaling instead of blacking out). A fix to #322 would almost certainly cure this as well so no need for the dupe. Thanks for reporting!
