### ISSUE TITLE
Indicate in the readme which libraries need to be installed in order to build

### ISSUE THREAD

**Issue by iwsfutcmd** [MFEK/glif#30]
In order to build Qglif on Ubuntu 20.04, I've noticed that I've had to install the following libraries (via `apt-get`):

* `libxcb-shape0-dev`
* `libxcb-xfixes0-dev`

I'm sure there are a few more that were needed that I already happened to have installed.

We should list the library requirements in README.md

**Comment by ctrlcctrlv** [comment]
I did notice @alerque added this:

https://github.com/mfeq/Qglif/blob/39876e75c677f5d71a961813450ab6096a74b33f/.github/workflows/rust.yml#L33

And did plan on mentioning it. Thanks for bringing this up so I don't forget.

Yesterday and today I got..._mildly_! distracted by #10...https://github.com/mfeq/spiro-sys/

And for some reason I decided it was a good use of time to write a Nom parser (`mod from`) for @raphlinus' plate files, and FontForge's very similar format...and then Inkscape's while I was at it:

```txt
spiro-rs:
  167 src/bezier.rs
  110 src/from/fontforge.rs
   10 src/from/inkscape.rs
    5 src/from/mod.rs
  212 src/from/plates.rs
  169 src/into/bezier.rs
   19 src/into/mod.rs
   40 src/into/spiro.rs
   78 src/lib.rs
```

Almost done :-) It has quite a nice API, and will have a few little tools methinks.
