### ISSUE TITLE
Switch to SDL2, drop `winit` ASAP. Point numbering broken, console broken on Linux due to `winit` kbd implementation being bad.

### ISSUE THREAD

**Issue by ctrlcctrlv** [MFEK/glif#31]
This says it all:

https://github.com/rust-windowing/winit/blob/386ead15a3e3fef5c0c02bd7491d3cc9a7a6e0aa/src/platform_impl/linux/x11/events.rs#L178

> ```
> //ffi::XK_numbersign => VirtualKeyCode::Numbersign
> ```

# 🤦‍♂️<sub>🤦‍♂️</sub><sub><sub>🤦‍♂️</sub></sub> 😱❗❗❗
Issue discovered by @eliheuer in his Twitch stream. Confirmed and cause found just now by @iwsfutcmd. 

I don't trust any software with code like this commented out period. They have no idea what they're doing in my humble opinion. The fact that <kbd>Subtract</kbd> and <kbd>Minus</kbd> were only recently unified is shocking as well.

So, this is an urgent issue. I had hoped not to need to rewrite `main.rs` again, but I don't mind given the severity of their keyboard handling.

[SDL2 supports Unicode input](https://wiki.libsdl.org/SDL_TextInputEvent), so console will still work without much worry about hooking OS APIs for IME's etc.

**Comment by ctrlcctrlv** [comment]
_Cf_. rust-windowing/winit#1656, rust-windowing/winit#812, btw. These are _years old_ issues, not new bugs.

**Comment by iwsfutcmd** [comment]
One suggestion is, when monitoring input events, make sure to track `SDL_TEXTINPUT` rather than `SDL_TEXTEDITING`, *especially* for the console. Nothing's worse than a program ignoring my IME because it thinks it knows what to do with my keystrokes better than I do.

**Comment by ctrlcctrlv** [comment]
Yup, I made sure Japanese IME worked in current `winit` console and will do the same for SDL2. 😃

**Comment by ctrlcctrlv** [comment]
OK, I've sort of gotten it working. Sorry for the delay, was focused on Spiro, which is a 1.0 feature per #10. (_Cf._ fontforge/libspiro#27, fontforge/libspiro#28 (bottom))

```
[2020-09-21T11:07:57Z INFO  Qglif] KeyDown { timestamp: 16780, window_id: 1, keycode: Some(RShift), scancode: Some(RShift), keymod: RSHIFTMOD | NUMMOD, repeat: false }
[2020-09-21T11:07:57Z INFO  Qglif] KeyDown { timestamp: 16943, window_id: 1, keycode: Some(Num3), scancode: Some(Num3), keymod: RSHIFTMOD | NUMMOD, repeat: false }
[2020-09-21T11:07:57Z INFO  Qglif] TextInput { timestamp: 16943, window_id: 1, text: "#" }
[2020-09-21T11:07:57Z INFO  Qglif] KeyUp { timestamp: 17065, window_id: 1, keycode: Some(Num3), scancode: Some(Num3), keymod: RSHIFTMOD | NUMMOD, repeat: false }
[2020-09-21T11:07:57Z INFO  Qglif] KeyUp { timestamp: 17095, window_id: 1, keycode: Some(RShift), scancode: Some(RShift), keymod: NUMMOD, repeat: false }
```

Much better&mdash;seems consistent too. 

![image](https://user-images.githubusercontent.com/838783/93760208-68470980-fbc0-11ea-92ac-f9259f6167dc.png)

I need to fix ImGui: the copied `support.rs` assumes winit. I also need to rewrite our event matching code, which shouldn't be too hard, and make _en masse_ tweaks to the event handlers, which should be doable with a few vim commands.

I wonder if @aclysma would be interested in a `support.rs` for SDL2? Skulpin seems to be in maintenance mode so I'm not sure.

**Comment by ctrlcctrlv** [comment]
Oh, and this seems to be working too @iwsfutcmd :-)

```
[2020-09-21T11:19:49Z INFO  Qglif] TextInput { timestamp: 169569, window_id: 1, text: "アイ・エム・イー" }
```

**Comment by ctrlcctrlv** [comment]
The war is over! https://twitter.com/fr_brennan/status/1373849754715705344

@MatthewBlanchard figured out that we could solve all of our switchover problems by just drawing Imgui with Skia. He's writing a Skia-based renderer for Imgui, which we'll use. Then we can drop all of the hacks which allow us to draw @ocornut's stock Imgui Vulkan renderer on top of Skulpin (Skia+Vulkan).

This allows us to flip over to SDL extremely easily. And because SDL can be used from WebAssembly…that means that MFEKglif _could_, _some day_, be compiled for the web browser. Really! Amazing work.
