### ISSUE TITLE
Mouse location is offset in the toolbar on Lubuntu.

### ISSUE THREAD

**Issue by MatthewBlanchard** [MFEK/glif#37]
The toolbar's selection is offset when mousing over or selecting a tool. 

Toolbar:
![Screenshot 2020-10-08 01:28:37](https://user-images.githubusercontent.com/310356/95418485-a012b880-0905-11eb-83ee-470f518f16ab.png)

Main view port:
![Screenshot 2020-10-08 01:29:46](https://user-images.githubusercontent.com/310356/95418544-c6385880-0905-11eb-8333-d9f15f3c6c82.png)

The main view port does not seem to suffer from this problem, and behaves correctly.

**Comment by ctrlcctrlv** [comment]
Probably a HiDPI issue...🤔

I got a tattoo yesterday and had to do a lot of media interviews the previous week. However my life is calming down. I have commits to push in re #31 and #10. 

Thanks for the note that I need to make sure I haven't broken HiDPI. I'd say hold off on trying to fix this unless it persists post closure of #31.

**Comment by ctrlcctrlv** [comment]
This is fixed due to #31 being closed.
