### ISSUE TITLE
Build is broken on latest nightly toolchain

### ISSUE THREAD

**Issue by Subject38** [MFEK/glif#396]
At least two dependencies use nightly features that no longer exist: font-kit and egui (there may be more but these were the two I saw when attempting to build on latest toolchain). Updating the egui version should fix the issues but font kit will currently not compile on the latest nightly https://github.com/servo/font-kit/issues/233. Opening this issue for tracking since our github CI is also broken as a result of this.

**Comment by Subject38** [comment]
I'm of half a mind that we should vendor font-kit since the fix has already been done on their end but it will likely not see an actual release for a month+.  I'm really not sure what the path forward should be though...

**Comment by sagudev** [comment]
You can use patch section in Cargo.toml to temporary override font-kit version from crates.io using git version. See https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section

**Comment by Subject38** [comment]
> You can use patch section in Cargo.toml to temporary override font-kit version from crates.io using git version. See https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section

I was aware that this was a thing, but am surprised nonetheless that the fix (on the fontkit side) was this simple. I just got it building on my M1 Macbook Pro running Asahi Fedora. Most of the other issues were thankfully resolved with the recent pull request being merged
