### ISSUE TITLE
can't compile skulpin-renderer

### ISSUE THREAD

**Issue by EwonRael** [MFEK/glif#61]
Hey.

I am not a coder, so I'm likely doing something wrong here, but I can't compile due to this error

`error[E0308]: mismatched types`

it tells me in my `.cargo/registry/src/github.com-1ecc6299db9ec823/skulpin-renderer-0.4.1/src/skia_support.rs` file it's expecting `Option<unsafe extern "system" fn() -> c_void>` and only finding `Option<unsafe extern "system" fn()>`

seems really silly to me because when I look at the `skia_support.rs` file it reads "`Option<unsafe extern "system" fn() -> c_void`" which is what it's claiming to want it to say so IDK what it's on about here.

I'm running `rustc 1.52.0-nightly`

let me know if there's any other info you'd need from me.

lovely project, truly the font editor we all need

**Comment by ctrlcctrlv** [comment]
Hello!

We're making major changes right now. Right now only the `vws-testing` branch builds. It'll be merged into `master` soon enough, but we still have to fix #27, #5, #13 and others before this is generally usable

**Comment by ctrlcctrlv** [comment]
This should build again :)
