### ISSUE TITLE
updating readme

### ISSUE THREAD

**Issue by EwonRael** [MFEK/glif#89]
right now glif won't run unless the .glif file is part of a UFO, the suggested command
`RUST_LOG=debug RUST_BACKTRACE=1 cargo run -- examples/Q_.glif`
doesn't run right now? (small)

also it needs vulkan drivers, which is mentioned for mac but not included in linux instructions

small in either case, not hard to figure out

**Comment by ctrlcctrlv** [comment]
What Linux distro do you use, and what package was needed for Vulkan?

**Comment by ctrlcctrlv** [comment]
I can't replicate this bug on master branch. I do get the expected log output:

```
[2021-04-26T09:24:35Z ERROR MFEKglif::ipc] Cannot set metrics, .glif file not part of a UFO!
```

But MFEKglif still launches.

![image](https://user-images.githubusercontent.com/838783/116060399-d882a580-a64f-11eb-8ba7-fa2d0a106b3a.png)

**Comment by EwonRael** [comment]
hmm. The program runs fine if I run `cargo run` without any flags, and at that point I can load a .glif file that isn't part of a UFO; it's only failing to run for me when I run `cargo run -- examples/Q_.glif` or some variation there of.

I'm running elementary os, and I installed `libvulkan1 libvulkan1:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386` not sure which ones were strictly necessary.

I am building from master, up to date
